<a href="https://colab.research.google.com/github/shubhpanchal/Artificial-Neural-Network/blob/main/BuildingANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
data = pd.read_csv('/content/drive/MyDrive/Deep Learning/ANN/Copy of Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
X = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [10]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [11]:
print(y)

[1 0 1 ... 1 1 0]


In [12]:
# Label encoding for gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [14]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [15]:
# One hot encoding for Geography
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
X= np.array(ct.fit_transform(X))

In [16]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [17]:
# split the dataset into train_test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Building an ANN**

In [19]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [20]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [21]:
# Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

In [23]:
# Adding the outpul layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**Training the ANN**

In [24]:
# Compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
# Training the ANN on the training set
ann.fit(X_train, y_train, batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5835 - accuracy: 0.7588
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4600 - accuracy: 0.7991
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4395 - accuracy: 0.8049
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.8092
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4227 - accuracy: 0.8126
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4172 - accuracy: 0.8184
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4129 - accuracy: 0.8195
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8249
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8290
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4038 - accura

Predict the Probability of a customer leaving the bank who is


1. from France
2. has a credit score of 600
3. who is a male
4. aged 40
5. customer since 3 years
6. has a balance of 60000  with the bank
7. has 2 active products
8. is active with the bank
9. and has an estimated salary of 50000

In [29]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

[[0.03536865]]


The probability fo the customer leaving the bank is 35.36%

In [30]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


Adding a threshold of 0.5. if probability is more than 0.5 then there are more chances of customer leaving the bank and will return True

In [31]:
# Predicting the test set results
y_pred = ann.predict(X_test) #this will return the probability outcome
y_pred = (y_pred>0.5) #this will return the Binary outcome.
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [32]:
# Making the confusion matrics
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1496   99]
 [ 189  216]]


0.856